wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: huggingface
    huggingface_version: 4.25.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.10.8
    start_time: 1674222376.787695
    t:
      1:
      - 1
      - 9
      - 11
      - 40
      - 41
      - 49
      - 51
      - 55
      - 71
      2:
      - 1
      - 9
      - 11
      - 40
      - 41
      - 49
      - 51
      - 55
      - 71
      3:
      - 7
      - 13
      - 23
      4: 3.10.8
      5: 0.13.7
      6: 4.25.1
      8:
      - 5
lr:
  desc: null
  value: 0.0001
num_hidden:
  desc: null
  value: 10
num_layers:
  desc: null
  value: 2
padding_str:
  desc: null
  value: <pad>
use_sliding:
  desc: null
  value: true
