lr: 0.0001
num_hidden: 10
num_layers: 2
padding_str: <PAD>
use_sliding: true
vocab: !!python/object:torchtext.vocab.vocab.Vocab
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - []
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  training: true
  vocab: !!python/object/new:torchtext._torchtext.Vocab
    state: !!python/tuple
    - 0.0.2
    - []
    - - <PAD>
      - '

        '
      - ' '
      - '!'
      - '"'
      - '#'
      - $
      - '%'
      - '&'
      - ''''
      - (
      - )
      - '*'
      - +
      - ','
      - '-'
      - .
      - /
      - '0'
      - '1'
      - '2'
      - '3'
      - '4'
      - '5'
      - '6'
      - '7'
      - '8'
      - '9'
      - ':'
      - ;
      - <
      - '='
      - '>'
      - '?'
      - '@'
      - A
      - B
      - C
      - D
      - E
      - F
      - G
      - H
      - I
      - J
      - K
      - L
      - M
      - N
      - O
      - P
      - Q
      - R
      - S
      - T
      - U
      - V
      - W
      - X
      - Y
      - Z
      - '['
      - \
      - ']'
      - ^
      - '`'
      - a
      - b
      - c
      - d
      - e
      - f
      - g
      - h
      - i
      - j
      - k
      - l
      - m
      - n
      - o
      - p
      - q
      - r
      - s
      - t
      - u
      - v
      - w
      - x
      - y
      - z
      - '|'
      - '~'
      - "\xA1"
      - "\xA3"
      - "\xA5"
      - "\xA7"
      - "\xB0"
      - "\xB1"
      - "\xB2"
      - "\xB3"
      - "\xB5"
      - "\xB7"
      - "\xBD"
      - "\xC1"
      - "\xC5"
      - "\xC6"
      - "\xC9"
      - "\xCD"
      - "\xCE"
      - "\xD6"
      - "\xD7"
      - "\xD8"
      - "\xDA"
      - "\xDC"
      - "\xDE"
      - "\xE0"
      - "\xE1"
      - "\xE2"
      - "\xE3"
      - "\xE4"
      - "\xE5"
      - "\xE7"
      - "\xE8"
      - "\xE9"
      - "\xEA"
      - "\xEB"
      - "\xEC"
      - "\xED"
      - "\xEE"
      - "\xF1"
      - "\xF2"
      - "\xF3"
      - "\xF4"
      - "\xF6"
      - "\xF8"
      - "\xFA"
      - "\xFB"
      - "\xFC"
      - "\u0100"
      - "\u0101"
      - "\u0103"
      - "\u0107"
      - "\u010D"
      - "\u0110"
      - "\u0111"
      - "\u0117"
      - "\u012B"
      - "\u0141"
      - "\u0142"
      - "\u0144"
      - "\u014C"
      - "\u014D"
      - "\u015B"
      - "\u015F"
      - "\u0161"
      - "\u016B"
      - "\u0173"
      - "\u017B"
      - "\u017E"
      - "\u01A1"
      - "\u01B0"
      - "\u02BB"
      - "\u02BF"
      - "\u0303"
      - "\u03B1"
      - "\u03B2"
      - "\u03B3"
      - "\u03BA"
      - "\u03BC"
      - "\u0421"
      - "\u0430"
      - "\u0432"
      - "\u0435"
      - "\u043A"
      - "\u043E"
      - "\u0441"
      - "\u0442"
      - "\u044F"
      - "\u0627"
      - "\u062D"
      - "\u0635"
      - "\u0644"
      - "\u0646"
      - "\u0647"
      - "\u094D"
      - "\u0E01"
      - "\u0E07"
      - "\u0E13"
      - "\u0E15"
      - "\u0E21"
      - "\u0E22"
      - "\u0E23"
      - "\u0E25"
      - "\u0E31"
      - "\u0E32"
      - "\u0E34"
      - "\u0E48"
      - "\u0E4C"
      - "\u10D2"
      - "\u10D3"
      - "\u10D5"
      - "\u10D6"
      - "\u10D8"
      - "\u10D9"
      - "\u10DD"
      - "\u10E0"
      - "\u10E1"
      - "\u10E3"
      - "\u10EA"
      - "\u10EB"
      - "\u10EC"
      - "\u10EE"
      - "\u10EF"
      - "\u10FB"
      - "\u1E25"
      - "\u1E43"
      - "\u1E45"
      - "\u1E63"
      - "\u1E6D"
      - "\u1E6F"
      - "\u1EA3"
      - "\u1EA5"
      - "\u1EA7"
      - "\u1EAF"
      - "\u1EC5"
      - "\u1EC7"
      - "\u1ECB"
      - "\u1EDB"
      - "\u1EED"
      - "\u1EF3"
      - "\u2011"
      - "\u2013"
      - "\u2014"
      - "\u2018"
      - "\u2019"
      - "\u201C"
      - "\u201D"
      - "\u201E"
      - "\u2020"
      - "\u2026"
      - "\u2032"
      - "\u2033"
      - "\u2044"
      - "\u20A4"
      - "\u20AC"
      - "\u20B9"
      - "\u2153"
      - "\u2154"
      - "\u2192"
      - "\u2212"
      - "\u2264"
      - "\u2609"
      - "\u266D"
      - "\u266F"
      - "\u3008"
      - "\u3009"
      - "\u306E"
      - "\u30A1"
      - "\u30A2"
      - "\u30AD"
      - "\u30B9"
      - "\u30C3"
      - "\u30C8"
      - "\u30D7"
      - "\u30E5"
      - "\u30EA"
      - "\u30EB"
      - "\u30F4"
      - "\u30FB"
      - "\u52D5"
      - "\u5834"
      - "\u5927"
      - "\u6226"
      - "\u653B"
      - "\u6A5F"
      - "\u6BBB"
      - "\u706B"
      - "\u792E"
      - "\u7A7A"
      - "\u968A"
      - "\uFEFF"
      - "\uFF5E"
    - []
